In [1]:
import pandas as pd
import numpy as np

In [2]:
import os

In [3]:
train_files = [os.path.join(os.getcwd(),"nliraw/train",i) for i in os.listdir(os.path.join(os.getcwd(),"nliraw/train"))]
train_files

['/home/jupyter/nlidata/nliraw/train/snli_1.0_train.jsonl',
 '/home/jupyter/nlidata/nliraw/train/snli_1.0_dev.jsonl',
 '/home/jupyter/nlidata/nliraw/train/multinli_0.9_train.jsonl',
 '/home/jupyter/nlidata/nliraw/train/mli_train_v1.jsonl']

In [4]:
dev_files = [os.path.join(os.getcwd(),"nliraw/dev",i) for i in os.listdir(os.path.join(os.getcwd(),"nliraw/dev"))]
test_files = [os.path.join(os.getcwd(),"nliraw/test",i) for i in os.listdir(os.path.join(os.getcwd(),"nliraw/test"))]

In [23]:
columnsneeded = ['gold_label','sentence1', "sentence2"]
train_dataframe= pd.DataFrame([], columns = columnsneeded)
for i in train_files:
    temp_dataFrame = pd.read_json(i,lines = True)
    train_dataframe = pd.concat([train_dataframe,temp_dataFrame])
train_dataframe=train_dataframe.reset_index()

['/home/jupyter/nlidata/nliraw/test/mli_dev_v1.jsonl',
 '/home/jupyter/nlidata/nliraw/test/.ipynb_checkpoints']

In [9]:
columnsneeded = ['gold_label','sentence1', "sentence2"]
test_dataframe= pd.DataFrame([], columns = columnsneeded)
for i in test_files[:-1]:
    temp_dataFrame = pd.read_json(i,lines = True)
    test_dataframe = pd.concat([test_dataframe,temp_dataFrame])
test_dataframe = test_dataframe.reset_index()

In [10]:
columnsneeded = ['gold_label','sentence1', "sentence2"]
dev_dataframe= pd.DataFrame([], columns = columnsneeded)
for i in dev_files:
    temp_dataFrame = pd.read_json(i,lines = True)
    dev_dataframe = pd.concat([dev_dataframe,temp_dataFrame])
dev_dataframe = dev_dataframe.reset_index()

In [11]:
train_dataframe = train_dataframe[train_dataframe.gold_label.isin(['entailment', 'contradiction', "neutral"])]
test_dataframe = test_dataframe[test_dataframe.gold_label.isin(['entailment', 'contradiction', "neutral"])]
dev_dataframe = dev_dataframe[dev_dataframe.gold_label.isin(['entailment', 'contradiction', "neutral"])]

,index,gold_label,sentence1,sentence2,annotator_labels,captionID,pairID,sentence1_binary_parse,sentence1_parse,sentence2_binary_parse,sentence2_parse,genre,promptID
0,0,neutral,A person on a horse jumps over a broken down a...,A person is training his horse for a competition.,[neutral],3416050480.jpg#4,3416050480.jpg#4r1n,( ( ( A person ) ( on ( a horse ) ) ) ( ( jump...,(ROOT (S (NP (NP (DT A) (NN person)) (PP (IN o...,( ( A person ) ( ( is ( ( training ( his horse...,(ROOT (S (NP (DT A) (NN person)) (VP (VBZ is) ...,NaN,NaN
1,1,contradiction,A person on a horse jumps over a broken down a...,"A person is at a diner, ordering an omelette.",[contradiction],3416050480.jpg#4,3416050480.jpg#4r1c,( ( ( A person ) ( on ( a horse ) ) ) ( ( jump...,(ROOT (S (NP (NP (DT A) (NN person)) (PP (IN o...,( ( A person ) ( ( ( ( is ( at ( a diner ) ) )...,(ROOT (S (NP (DT A) (NN person)) (VP (VBZ is) ...,NaN,NaN
2,2,entailment,A person on a horse jumps over a broken down a...,"A person is outdoors, on a horse.",[entailment],3416050480.jpg#4,3416050480.jpg#4r1e,( ( ( A person ) ( on ( a horse ) ) ) ( ( jump...,(ROOT (S (NP (NP (DT A) (NN person)) (PP (IN o...,"( ( A person ) ( ( ( ( is outdoors ) , ) ( on ...",(ROOT (S (NP (DT A) (NN person)) (VP (VBZ is) ...,NaN,NaN
3,3,neutral,Children smiling and waving at camera,They are smiling at their parents,[neutral],2267923837.jpg#2,2267923837.jpg#2r1n,( Children ( ( ( smiling and ) waving ) ( at c...,(ROOT (NP (S (NP (NNP Children)) (VP (VBG smil...,( They ( are ( smiling ( at ( their parents ) ...,(ROOT (S (NP (PRP They)) (VP (VBP are) (VP (VB...,NaN,NaN
4,4,entailment,Children smiling and waving at camera,There are children present,[entailment],2267923837.jpg#2,2267923837.jpg#2r1e,( Children ( ( ( smiling and ) waving ) ( at c...,(ROOT (NP (S (NP (NNP Children)) (VP (VBG smil...,( There ( ( are children ) present ) ),(ROOT (S (NP (EX There)) (VP (VBP are) (NP (NN...,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
964081,11227,contradiction,"He received 2U PRBC, underwent tagged RBC scan...",The patient has not had a nuclear medicine te...,NaN,NaN,2449d50a-66c7-11e7-828c-f45c89b91419,"( He ( ( ( ( received ( 2U PRBC ) ) , ) ( unde...",(ROOT (S (NP (PRP He)) (VP (VP (VBD received) ...,( ( The patient ) ( ( ( has not ) ( had ( a ( ...,(ROOT (S (NP (DT The) (NN patient)) (VP (VBZ h...,NaN,NaN
964082,11228,neutral,"He received 2U PRBC, underwent tagged RBC scan...",The patient has an active bleed.,NaN,NaN,2449d712-66c7-11e7-9d9e-f45c89b91419,"( He ( ( ( ( received ( 2U PRBC ) ) , ) ( unde...",(ROOT (S (NP (PRP He)) (VP (VP (VBD received) ...,( ( The patient ) ( ( has ( an ( active bleed ...,(ROOT (S (NP (DT The) (NN patient)) (VP (VBZ h...,NaN,NaN
964083,11229,entailment,Pregnancy was complicated by spotting at 18 we...,The patient reported bloody discharge during ...,NaN,NaN,2449d9ae-66c7-11e7-8338-f45c89b91419,( Pregnancy ( ( was ( complicated ( by ( ( ( s...,(ROOT (S (NP (NN Pregnancy)) (VP (VBD was) (VP...,( ( The patient ) ( ( reported ( bloody discha...,(ROOT (NP (NP (DT The) (NN patient)) (VP (VBD ...,NaN,NaN
964084,11230,contradiction,Pregnancy was complicated by spotting at 18 we...,Pregnancy was uncomplicated,NaN,NaN,2449db5e-66c7-11e7-b9aa-f45c89b91419,( Pregnancy ( ( was ( complicated ( by ( ( ( s...,(ROOT (S (NP (NN Pregnancy)) (VP (VBD was) (VP...,( Pregnancy ( was uncomplicated ) ),(ROOT (S (NP (NN Pregnancy)) (VP (VBD was) (AD...,NaN,NaN
964085,11231,neutral,Pregnancy was complicated by spotting at 18 we...,She has a history of spontaneous abortion,NaN,NaN,2449dcee-66c7-11e7-9099-f45c89b91419,( Pregnancy ( ( was ( complicated ( by ( ( ( s...,(ROOT (S (NP (NN Pregnancy)) (VP (VBD was) (VP...,( She ( has ( ( a history ) ( of ( spontaneous...,(ROOT (S (NP (PRP She)) (VP (VBZ has) (NP (NP ...,NaN,NaN

In [33]:
columnsneeded = ['gold_label',"index","sentence1","sentence2"]
train_dataframe = pd.concat([train_dataframe.iloc[350000:700000][columnsneeded],pd.read_json('/home/jupyter/nlidata/nliraw/train/mli_train_v1.jsonl', lines = True).reset_index()[columnsneeded]]).drop(["index"], axis =1).drop_duplicates()
train_dataframe = train_dataframe.reset_index()
train_dataframe[columnsneeded].to_csv("train.tsv",sep = "\t", index = False, encoding = "UTF-8")
test_dataframe[columnsneeded].to_csv("test.tsv",sep = "\t", index = False, encoding = "UTF-8")
dev_dataframe[columnsneeded].to_csv("dev.tsv",sep = "\t", index = False, encoding = "UTF-8")

In [29]:
pd.read_json('/home/jupyter/nlidata/nliraw/train/mli_train_v1.jsonl', lines = True).reset_index()[columnsneeded]

,gold_label,index,sentence1,sentence2
0,entailment,0,Labs were notable for Cr 1.7 (baseline 0.5 per...,Patient has elevated Cr
1,contradiction,1,Labs were notable for Cr 1.7 (baseline 0.5 per...,Patient has normal Cr
2,neutral,2,Labs were notable for Cr 1.7 (baseline 0.5 per...,Patient has elevated BUN
3,entailment,3,Nystagmus and twiching of R arm was noted.,The patient had abnormal neuro exam.
4,contradiction,4,Nystagmus and twiching of R arm was noted.,The patient has a normal neuro exam.
...,...,...,...,...
11227,contradiction,11227,"He received 2U PRBC, underwent tagged RBC scan...",The patient has not had a nuclear medicine te...
11228,neutral,11228,"He received 2U PRBC, underwent tagged RBC scan...",The patient has an active bleed.
11229,entailment,11229,Pregnancy was complicated by spotting at 18 we...,The patient reported bloody discharge during ...
11230,contradiction,11230,Pregnancy was complicated by spotting at 18 we...,Pregnancy was uncomplicated
11231,neutral,11231,Pregnancy was complicated by spotting at 18 we...,She has a history of spontaneous abortion

In [32]:
pd.concat([train_dataframe.iloc[350000:700000][columnsneeded],pd.read_json('/home/jupyter/nlidata/nliraw/train/mli_train_v1.jsonl', lines = True).reset_index()[columnsneeded]]).drop(["index"],axis = 1)

,gold_label,sentence1,sentence2
0,entailment,Labs were notable for Cr 1.7 (baseline 0.5 per...,Patient has elevated Cr
1,contradiction,Labs were notable for Cr 1.7 (baseline 0.5 per...,Patient has normal Cr
2,neutral,Labs were notable for Cr 1.7 (baseline 0.5 per...,Patient has elevated BUN
3,entailment,Nystagmus and twiching of R arm was noted.,The patient had abnormal neuro exam.
4,contradiction,Nystagmus and twiching of R arm was noted.,The patient has a normal neuro exam.
...,...,...,...
11227,contradiction,"He received 2U PRBC, underwent tagged RBC scan...",The patient has not had a nuclear medicine te...
11228,neutral,"He received 2U PRBC, underwent tagged RBC scan...",The patient has an active bleed.
11229,entailment,Pregnancy was complicated by spotting at 18 we...,The patient reported bloody discharge during ...
11230,contradiction,Pregnancy was complicated by spotting at 18 we...,Pregnancy was uncomplicated
11231,neutral,Pregnancy was complicated by spotting at 18 we...,She has a history of spontaneous abortion

In [19]:
train_dataframe = pd.concat([train_dataframe.iloc[:350000][columnsneeded],pd.read_json('/home/jupyter/nlidata/nliraw/train/mli_train_v1.jsonl', lines = True).reset_index()[columnsneeded]]).drop_duplicates()
train_dataframe

,gold_label,sentence1,sentence2
0,neutral,A person on a horse jumps over a broken down a...,A person is training his horse for a competition.
1,contradiction,A person on a horse jumps over a broken down a...,"A person is at a diner, ordering an omelette."
2,entailment,A person on a horse jumps over a broken down a...,"A person is outdoors, on a horse."
3,neutral,Children smiling and waving at camera,They are smiling at their parents
4,entailment,Children smiling and waving at camera,There are children present
...,...,...,...
11227,contradiction,"He received 2U PRBC, underwent tagged RBC scan...",The patient has not had a nuclear medicine te...
11228,neutral,"He received 2U PRBC, underwent tagged RBC scan...",The patient has an active bleed.
11229,entailment,Pregnancy was complicated by spotting at 18 we...,The patient reported bloody discharge during ...
11230,contradiction,Pregnancy was complicated by spotting at 18 we...,Pregnancy was uncomplicated
11231,neutral,Pregnancy was complicated by spotting at 18 we...,She has a history of spontaneous abortion

In [ ]:
train_dataframe.gold_label.value_counts()

In [20]:
import pandas as pd
train = pd.read_csv("train.tsv",sep = "\t",header = None)
train.columns = columnsneeded

In [13]:
columnsneeded = ['gold_label',"index","sentence1","sentence2"]

In [13]:
train.iloc[:50000].to_csv("train.tsv",sep = "\t",header = False, index = False, encoding = "UTF-8")

In [12]:
train

,0,1,2,3
0,neutral,0,A person on a horse jumps over a broken down a...,A person is training his horse for a competition.
1,contradiction,1,A person on a horse jumps over a broken down a...,"A person is at a diner, ordering an omelette."
2,entailment,2,A person on a horse jumps over a broken down a...,"A person is outdoors, on a horse."
3,neutral,3,Children smiling and waving at camera,They are smiling at their parents
4,entailment,4,Children smiling and waving at camera,There are children present
...,...,...,...,...
963138,contradiction,11227,"He received 2U PRBC, underwent tagged RBC scan...",The patient has not had a nuclear medicine te...
963139,neutral,11228,"He received 2U PRBC, underwent tagged RBC scan...",The patient has an active bleed.
963140,entailment,11229,Pregnancy was complicated by spotting at 18 we...,The patient reported bloody discharge during ...
963141,contradiction,11230,Pregnancy was complicated by spotting at 18 we...,Pregnancy was uncomplicated
963142,neutral,11231,Pregnancy was complicated by spotting at 18 we...,She has a history of spontaneous abortion

In [43]:
pd.read_csv("train.tsv",sep = "\t",header = None)

,0,1,2,3
0,neutral,0,A person on a horse jumps over a broken down a...,A person is training his horse for a competition.
1,contradiction,1,A person on a horse jumps over a broken down a...,"A person is at a diner, ordering an omelette."
2,entailment,2,A person on a horse jumps over a broken down a...,"A person is outdoors, on a horse."
3,neutral,3,Children smiling and waving at camera,They are smiling at their parents
4,entailment,4,Children smiling and waving at camera,There are children present
...,...,...,...,...
199757,contradiction,199996,Male in a white sweatshirt engaged in what app...,The male is ignoring the female.
199758,neutral,199997,Male in a white sweatshirt engaged in what app...,The male is asking the female to marry him.
199759,contradiction,199998,a couple kissing at the top of the stairs on a...,The couple is swimming.
199760,neutral,199999,a couple kissing at the top of the stairs on a...,The couple know eachother.
199761,entailment,200000,a couple kissing at the top of the stairs on a...,The couple are outside.

In [23]:
train = pd.concat([train.iloc[:350000],pd.read_json('/home/jupyter/nlidata/nliraw/train/mli_train_v1.jsonl', lines = True).reset_index()[columnsneeded]])
train.to_csv("train.tsv",sep = "\t",header = False, index = False, encoding = "UTF-8")

In [24]:
import os
os.getcwd()

'/home/jupyter/nlidata'

In [114]:
test_ground = pd.read_csv("/home/jupyter/output200000/test_results.tsv", sep = "\t",header = None,names = ["contradiction","entailment", "neutral"])
test_ground["pred"]=test_ground.idxmax(axis = "columns")

In [65]:
test_ground

       contradiction  entailment   neutral
0           0.000048    0.998100  0.001852
1           0.999918    0.000012  0.000071
2           0.000065    0.000211  0.999724
3           0.000031    0.000196  0.999773
4           0.000287    0.000334  0.999379
...              ...         ...       ...
11213       0.997945    0.000026  0.002029
11214       0.000120    0.001489  0.998391
11215       0.000076    0.000920  0.999004
11216       0.999731    0.000134  0.000136
11217       0.000096    0.000271  0.999633

[11218 rows x 3 columns]

In [55]:
test_dataframe = pd.read_csv("test.tsv", sep = "\t")

In [58]:
test_dataframe.columns = columnsneeded

In [66]:
test_ground["prediction"] = test_ground.idxmax(axis = "columns")

In [68]:
testresult = pd.concat([test_dataframe,test_ground["prediction"]], axis = 1)

In [74]:
test

0.848814405419861

In [89]:
test_files.remove('/home/jupyter/nlidata/nliraw/test/.ipynb_checkpoints')

In [90]:
test_files

['/home/jupyter/nlidata/nliraw/test/mli_dev_v1.jsonl']

In [101]:
test_dataframe[columnsneeded].to_csv("test.tsv",sep = "\t",header = False, index = False, encoding = "UTF-8")

In [99]:
columnsneeded = ['gold_label',"index", 'sentence1', 'sentence2']

In [103]:
testog = test_dataframe.iloc[1:,]

In [116]:
testres = pd.concat([testog[columnsneeded].reset_index(),test_ground["pred"] ], axis = 1)

In [106]:
test_ground

      contradiction  entailment   neutral
0          0.002591    0.000219  0.997190
1          0.000234    0.000957  0.998809
2          0.000088    0.999496  0.000415
3          0.999787    0.000077  0.000136
4          0.000086    0.000150  0.999765
...             ...         ...       ...
1389       0.997945    0.000026  0.002029
1390       0.000120    0.001489  0.998391
1391       0.000076    0.000920  0.999004
1392       0.999731    0.000134  0.000136
1393       0.000096    0.000271  0.999633

[1394 rows x 3 columns]

In [107]:
testog

,index,gold_label,sentence1,sentence2,pairID,sentence1_parse,sentence1_binary_parse,sentence2_parse,sentence2_binary_parse
1,1,contradiction,"No history of blood clots or DVTs, has never h...",Patient has had multiple PEs,1892c578-66c7-11e7-97cf-f45c89b91419,(ROOT (S (NP (NP (DT No) (NN history)) (PP (IN...,( ( ( No history ) ( of ( ( ( blood clots ) or...,(ROOT (S (NP (NN Patient)) (VP (VBZ has) (VP (...,( Patient ( has ( had ( multiple PEs ) ) ) )
2,2,neutral,"No history of blood clots or DVTs, has never h...",Patient has CAD,1892c8ac-66c7-11e7-9f8f-f45c89b91419,(ROOT (S (NP (NP (DT No) (NN history)) (PP (IN...,( ( ( No history ) ( of ( ( ( blood clots ) or...,(ROOT (S (NP (NN Patient)) (VP (VBZ has) (VP (...,( Patient ( has CAD ) )
3,3,entailment,Over the past week PTA he has been more somnol...,He has been less alert over the past week,1892cadc-66c7-11e7-92e6-f45c89b91419,(ROOT (S (PP (IN Over) (NP (DT the) (JJ past) ...,( ( Over ( the ( past week ) ) ) ( PTA ( he ( ...,(ROOT (S (NP (PRP He)) (VP (VBZ has) (VP (VBN ...,( He ( has ( ( been ( less alert ) ) ( over ( ...
4,4,contradiction,Over the past week PTA he has been more somnol...,Over the past week he has been alert and orie...,1892cce4-66c7-11e7-8c22-f45c89b91419,(ROOT (S (PP (IN Over) (NP (DT the) (JJ past) ...,( ( Over ( the ( past week ) ) ) ( PTA ( he ( ...,(ROOT (S (PP (IN Over) (NP (DT the) (JJ past) ...,( ( Over ( the ( past week ) ) ) ( he ( has ( ...
5,5,neutral,Over the past week PTA he has been more somnol...,He is disorientated and complains of weakness,1892cecc-66c7-11e7-94f1-f45c89b91419,(ROOT (S (PP (IN Over) (NP (DT the) (JJ past) ...,( ( Over ( the ( past week ) ) ) ( PTA ( he ( ...,(ROOT (S (NP (PRP He)) (VP (VP (VBZ is) (VP (V...,( He ( ( ( is disorientated ) and ) ( complain...
...,...,...,...,...,...,...,...,...,...
1390,1390,contradiction,CAD s/p coronary bypass surgery [**3-16**]- LI...,The patient has no heart disease,189fc514-66c7-11e7-b374-f45c89b91419,(ROOT (SINV (NP (NN CAD) (NN s/p) (JJ coronary...,( ( ( ( CAD ( s/p ( coronary ( bypass surgery ...,(ROOT (S (NP (DT The) (NN patient)) (VP (VBZ h...,( ( The patient ) ( has ( no ( heart disease )...
1391,1391,neutral,CAD s/p coronary bypass surgery [**3-16**]- LI...,The patient has a history of myocardial infar...,189fc6f8-66c7-11e7-8314-f45c89b91419,(ROOT (SINV (NP (NN CAD) (NN s/p) (JJ coronary...,( ( ( ( CAD ( s/p ( coronary ( bypass surgery ...,(ROOT (S (NP (DT The) (NN patient)) (VP (VBZ h...,( ( The patient ) ( has ( ( a history ) ( of (...
1392,1392,entailment,Her respiratory status seems to improve with n...,The patient is short of breath.,189fc892-66c7-11e7-b6c4-f45c89b91419,(ROOT (S (NP (PRP$ Her) (JJ respiratory) (NN s...,( ( Her ( respiratory status ) ) ( ( seems ( t...,(ROOT (S (NP (DT The) (NN patient)) (VP (VBZ i...,( ( The patient ) ( ( is ( short ( of breath )...
1393,1393,contradiction,Her respiratory status seems to improve with n...,The patient has normal breathing.,189fca18-66c7-11e7-9825-f45c89b91419,(ROOT (S (NP (PRP$ Her) (JJ respiratory) (NN s...,( ( Her ( respiratory status ) ) ( ( seems ( t...,(ROOT (S (NP (DT The) (NN patient)) (VP (VBZ h...,( ( The patient ) ( ( has ( normal breathing )...
1394,1394,neutral,Her respiratory status seems to improve with n...,The patient has COPD.,189fcb92-66c7-11e7-a450-f45c89b91419,(ROOT (S (NP (PRP$ Her) (JJ respiratory) (NN s...,( ( Her ( respiratory status ) ) ( ( seems ( t...,(ROOT (S (NP (DT The) (NN patient)) (VP (VBZ h...,( ( The patient ) ( ( has COPD ) . ) )

In [112]:
test_ground.idxmax(axis = "columns")

0             neutral
1             neutral
2          entailment
3       contradiction
4             neutral
            ...
1389    contradiction
1390          neutral
1391          neutral
1392    contradiction
1393          neutral
Length: 1394, dtype: object

In [119]:
(testres.gold_label == testres.pred).sum()/len(testres)

0.7166427546628408